### PR TITLE
Add feature:  Table of Contents support unlimited levels

### PR DESCRIPTION
**Pull request by ystyle**
Add feature:  Table of Contents support unlimited levels
how to add subSection https://github.com/bmaupin/go-epub/issues/10

ebook-viewer_2019-11-16_02-08-56

### CODE REVIEW

**Comment by sndnvaps** [comment]
@ystyle 
good job. thanks a lot.

**Comment by bmaupin** [comment]
I'm finally getting around to this, and it looks like this PR is generating a handful of EPUB validation errors:

```
ERROR(RSC-005): My EPUB.epub/EPUB/nav.xhtml(13,20): Error while parsing file: element "ol" incomplete; missing required element "li"
ERROR(RSC-005): My EPUB.epub/EPUB/nav.xhtml(17,20): Error while parsing file: element "ol" incomplete; missing required element "li"
ERROR(RSC-005): My EPUB.epub/EPUB/nav.xhtml(21,20): Error while parsing file: element "ol" incomplete; missing required element "li"
ERROR(RSC-005): My EPUB.epub/EPUB/nav.xhtml(20,39): Error while parsing file: Anchors within nav elements must contain text
ERROR(RSC-005): My EPUB.epub/EPUB/toc.ncx(15,15): Error while parsing file: element "navMap" not allowed here; expected the element end-tag or element "navPoint"
ERROR(RSC-005): My EPUB.epub/EPUB/toc.ncx(15,24): Error while parsing file: element "navMap" incomplete; missing required element "navPoint"
ERROR(RSC-005): My EPUB.epub/EPUB/toc.ncx(22,15): Error while parsing file: element "navMap" not allowed here; expected the element end-tag or element "navPoint"
ERROR(RSC-005): My EPUB.epub/EPUB/toc.ncx(22,24): Error while parsing file: element "navMap" incomplete; missing required element "navPoint"
ERROR(RSC-005): My EPUB.epub/EPUB/toc.ncx(29,15): Error while parsing file: element "navMap" not allowed here; expected the element end-tag or element "navPoint"
ERROR(RSC-005): My EPUB.epub/EPUB/toc.ncx(29,24): Error while parsing file: element "navMap" incomplete; missing required element "navPoint"
WARNING(NAV-011): My EPUB.epub/EPUB/nav.xhtml(20,39): "toc" nav must be in reading order; link target "EPUB/xhtml/cover.xhtml" is before the previous link’s target in spine order.
```

I'll take a look and see how much work will be involved to fix these.

I also updated the CI to run EPUBCheck on any pull requests to hopefully catch this sort of issue sooner in the future (https://github.com/bmaupin/go-epub/commit/a3e758ba84d5d3657554443f354b996c58e33964).

**Comment by bmaupin** [comment]
To resolve:

- [ ] `AddSubSection` is not tested as part of the EPUB validation test
- [ ] Validation errors (likely caused by `AddSubSection` not being part of the validation test, meaning a valid EPUB isn't generated if `AddSubSection` isn't used)
- [ ] Should have some kind of minimal functionality test just for `AddSubSection`
- [ ] Documentation for `AddSubSection` is missing (although there is an example, which will generate some documentation)
- [ ] Documentation for `AddSection` has been moved to `addSection`
- [ ] Some code in write.go is commented instead of being removed
  - [ ] Figure out how to handle this
  - [ ] Update documentation if `AddSection` functionality is changed
- [ ] toc.ncx IDs now contain UUIDS; is this necessary?

**Comment by ystyle** [comment]
### test code: 
```go
package main

import "github.com/bmaupin/go-epub"

func main() {
	e := epub.NewEpub("test")
	e.SetAuthor("ystyle")
	e.SetDescription("test epub")
	e.AddSection("Section 1 body", "Section 1", "", "")
	e.AddSection("Section 2 body", "Section 2", "", "")
	ref3, err := e.AddSection("Section 3 body", "Section 3", "", "")
	if err != nil {
		panic(err)
	}
	e.AddSubSection("Section 3.1 body", "Section 3.1", "", "", ref3)
	e.AddSubSection("Section 3.2 body", "Section 3.2", "", "", ref3)
	e.Write("test.epub")
}
```

### issue: 

```shell
 ✘ ystyle@Archlinux  ~/Code/Go/epub-demo  epubcheck test.epub
Validating using EPUB version 3.2 rules.
ERROR(RSC-005): test.epub/EPUB/nav.xhtml(13,20): Error while parsing file: element "ol" incomplete; missing required element "li"
ERROR(RSC-005): test.epub/EPUB/nav.xhtml(17,20): Error while parsing file: element "ol" incomplete; missing required element "li"
ERROR(RSC-005): test.epub/EPUB/nav.xhtml(24,24): Error while parsing file: element "ol" incomplete; missing required element "li"
ERROR(RSC-005): test.epub/EPUB/nav.xhtml(28,24): Error while parsing file: element "ol" incomplete; missing required element "li"

Check finished with errors
Messages: 0 fatals / 4 errors / 0 warnings / 0 infos

EPUBCheck completed

```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
  <head>
    <title>test</title>
  </head>
  <body>
    <nav epub:type="toc">
      <h1>Table of Contents</h1>
      <ol>
        <li>
          <a href="xhtml/section0001.xhtml">Section 1</a>
          <ol></ol>
        </li>
        <li>
          <a href="xhtml/section0002.xhtml">Section 2</a>
          <ol></ol>
        </li>
        <li>
          <a href="xhtml/section0003.xhtml">Section 3</a>
          <ol>
            <li>
              <a href="xhtml/section0004.xhtml">Section 3.1</a>
              <ol></ol>
            </li>
            <li>
              <a href="xhtml/section0005.xhtml">Section 3.2</a>
              <ol></ol>
            </li>
          </ol>
        </li>
      </ol>
    </nav>
</body>
</html>
```

    I don't know how to remove the empty ol


```go
// toc.go:L62
type tocNavBody struct {
	XMLName  xml.Name      `xml:"nav"`
	EpubType string        `xml:"epub:type,attr"`
	H1       string        `xml:"h1"`
	Links    []*tocNavItem `xml:"ol>li"`
}

type tocNavItem struct {
	A        tocNavLink    `xml:"a"`
	Children []*tocNavItem `xml:"ol>li"`
}

type tocNavLink struct {
	XMLName xml.Name `xml:"a"`
	Href    string   `xml:"href,attr"`
	Data    string   `xml:",chardata"`
}
```

**Comment by bmaupin** [comment]
> I don't know how to remove the empty ol

There's an `omitempty` option that can be used:

> - a field with a tag including the "omitempty" option is omitted
>   if the field value is empty. The empty values are false, 0, any
>   nil pointer or interface value, and any array, slice, map, or
>   string of length zero.

https://pkg.go.dev/encoding/xml#Marshal

The trick is it only works on an element and not parent elements: https://stackoverflow.com/a/27246583/399105

I remember playing with it a little bit and I think I got that part working, in case this helps:

```go
type tocNavBody struct {
	XMLName  xml.Name      `xml:"nav"`
	EpubType string        `xml:"epub:type,attr"`
	H1       string        `xml:"h1"`
	List    tocNavList `xml:"ol"`
}

type tocNavList struct {
	XMLName xml.Name `xml:"ol,omitempty"`
	Items []tocNavItem `xml:"li"`
}

type tocNavItem struct {
	A tocNavLink `xml:"a"`
	List *tocNavList
}

type tocNavLink struct {
	Href    string   `xml:"href,attr"`
	Data    string   `xml:",chardata"`
}
```

**Comment by bmaupin** [comment]
Closing in favour of #58

**Pull request closed without merging**
