### PR TITLE
RTL support

### PR DESCRIPTION
**Pull request by Monirzadeh**
It adds basic RTL support for go-epub

### CODE REVIEW

**Comment by bmaupin** [comment]
@Monirzadeh correct, it looks like one of the remote resources for one of the tests is returning a 404, as per #66 

Regarding this PR, I'm having trouble understanding what it's for. We already have a method to set [`page-progression-direction`](https://www.w3.org/TR/epub-33/#attrdef-spine-page-progression-direction). Isn't that enough for RTL support?

Thanks!

**Comment by bmaupin** [comment]
Ah, I might've misunderstood, maybe `page-progression-direction` is just the direction that the pages turn, and not the way the characters are ordered.

At any rate, I want to get this fixed but I'd like to better understand the problem first.

1. When you say it doesn't "work", what does that mean?
2. Do you have a sample RTL EPUB I could take a look at? Preferably one with `dir` (and PPD if possible) set. I'm curious to see for myself what the different options do.
3. What Epub reader are you using?

Thanks!

**Comment by bmaupin** [comment]
Ah ok, I think I understand the problem now. The characters of the words are all in correct RTL order, but without `dir`, the text is improperly justified and even out of order.

I was going through the EPUB 3.3 spec, and it looks like `dir` can also be set in the package document file. Did you try that? https://www.w3.org/TR/epub-33/#attrdef-dir

**Comment by owulveryck** [comment]
I don't like the idea of merging something that will break the tests, but my understanding is that it is unrelated to this change.
Therefore, I am ok to merge.

**Comment by bmaupin** [comment]
> I don't like the idea of merging something that will break the tests

Agreed. @Monirzadeh if you can merge or rebase this off the main branch, we can merge it.

I won't be available for the rest of the week but @owulveryck feel free to merge it if the tests are passing.

Thanks!

**Pull request merged**
