### PR TITLE
Fix incorrect ID generation for images in manifest

### LINKED ISSUE #14: Incorrect manifest ids created
I add an image with `AddImage(filename, destpath)`, but then the image name starts with an digit, I get an error from epubcheck. 

For example when I add `07-savepages.png`, the resulting line in `package.opf` in the manifest section is:

```xml
<item id="07-savepages.png" href="images/07-savepages.png" media-type="image/png"></item>
```

The `07-savepages.png` is not a valid XML id.

### PR DESCRIPTION
**Pull request by pgundlach**
The media name was taken as the xml id for the manifest. This
breaks XML rules when for example the image file name

* starts with a number
* contains spaces or colons

This fixes #14

### CODE REVIEW

**Comment by bmaupin** [comment]
Thanks for the pull request! I'm sorry it's taken me so long to look at it.

Unfortunately it has a number of issues:

- You've updated the readme to remove badges and point the links to your fork
- Other parts of the code point to your fork, e.g. example_test.go, go.mod, etc. (maybe this is a limitation of Go? I always found it a bit pedantic)
- The title of this PR is "Fix incorrect ID generation for images in manifest" but it looks like it also contains functionality to add subsections? I suppose there's no rule against doing this but ideally each feature would be a separate pull request from a separate feature branch in the fork
- In the feature to add subsections you've modified the `AddSection` function, but I would prefer not to make breaking changes to the API. Given that there's [another PR to add subsections](https://github.com/bmaupin/go-epub/pull/17) that doesn't contain breaking changes, I'll probably merge that one instead.

I'll close this for now but if it's something that still interests you feel free to address the above concerns and reopen it. I'll leave https://github.com/bmaupin/go-epub/issues/14 open in the meantime.

Thanks!

**Comment by pgundlach** [comment]
That was most likely an error on my side. I have forked the project and updated it for my needs, but this should not have gone into the pull request. 

If I remember correctly I still use the code (with my patches). I might have a another look again.

Thank you for your response and sorry for the noise!

**Comment by bmaupin** [comment]
I don't remember why I closed this instead of leaving it open so it could be changed. Unfortunately I can't reopen it since I've since renamed the master branch. But it looks like the fix for #14 is in its own commit so it should be fairly trivial to merge. I'll see if I can create a separate PR with just that commit.

**Comment by bmaupin** [comment]
This was resolved with #41

**Pull request closed without merging**
