### PR TITLE
Better error Handling

### LINKED ISSUE #49: Better error handling
Hi!

This library is using extensively the `panic` function. I guess that, in most case, we should raise an error instead of panicing.

For example, I am using this library in a tool that fetches article on the web, apply a reading mode and create an epub.
Depending on the HTML structure, some stuffs are failing (bad src tags for images for examples, cf #45 ).
We would benefit from a proper error handling. The drawback is that it would change the API.

for example 

```go
func (e *Epub) SetCover(internalImagePath string, internalCSSPath string) {
...
}
```

could return an error if it cannot set the cover:

```go
func (e *Epub) SetCover(internalImagePath string, internalCSSPath string) error {
...
}
```

I can take the action to post a PR for discussion if you want.

### LINKED ISSUE #63: Option for writeMedia to log warnings and continue instead of returning at the first error
Coming from [https://github.com/lapwat/papeer/issues/12](https://github.com/lapwat/papeer/issues/12)
Is it possible to just log a warning instead of returning an error?
In my particular case, there seems to be a broken img link that is halting the whole process, I really don't care if a single image is not downloaded so I would still like for the process to continue.

### PR DESCRIPTION
**Pull request by Monirzadeh**
This Pull request try to remove `panic` from the code.
it should finally should
close #49
close #63 

# TODO:
- [X] Remove all panic [31 / 31]
- [X] Update unit test
- [x] fix macos error
**this todo list will update in future*

@bmaupin it is not complete yet. I want remove all `panic` form code step by step. please review current state so i can understand your thought about this.
i will remove more unneeded panic from code in future.

### CODE REVIEW

**Comment by bmaupin** [comment]
Oh wow, thanks for starting this! This is much needed. I like your approach of doing it a little bit at a time.

I took a quick look, and yes, my general thought was basically to replace all of the usages of `panic` with error codes.

For now I only have one comment, regarding https://github.com/pkg/errors ; this package is no longer maintained and the GitHub repo has been archived.

From what I can tell, it looks like it wraps errors to provide context, which sounds great. But since that package isn't maintained, I'm hesitant to add it to this project. You can see at this issue that lots of other projects are abandoning it: https://github.com/pkg/errors/issues/245

I think it would be best to either find an alternative or just leave it out. In theory if the error messages are descriptive enough, maybe we don't need it? This library is simple enough that maybe it could manage without. For instance, it looks like you're essentially wrapping errors yourself (without this library) when you do things like this:

```go
return nil, fmt.Errorf("Can't create NewEpub: %s", err)
```

I'll try to take a closer look at this PR when I get a chance. Right now everything's blocked by the broken tests so I'd like to get #66 merged before merging anything else.

Thanks!

**Comment by fmartingr** [comment]
> For now I only have one comment, regarding https://github.com/pkg/errors ; this package is no longer maintained and the GitHub repo has been archived.

We have this due in shiori ourselves. In order to wrap errors (the "new" way) you can use the `%w` denominator when creating an error: `fmt.Errorf("error 1: %w", err)`

**Comment by bmaupin** [comment]
> @bmaupin remain 4 `panic` in `write.go` can you explain mere about them?

It looks like the first one will get called if there's an error when the file being added to the zip file gets closed.

It looks like the others will get called if there's an error when the zip file writer is being closed due to a previous error in the process of writing the zip file.

**Comment by fmartingr** [comment]
> @bmaupin can we have an new release after this PR merge?

Remember that you can start working using the commit sha as version in the dependencies until this PR is merged and released. Once the release is made we can point it towards the proper release.

**Pull request closed without merging**
